// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.API.EF;

#nullable disable

namespace TicketBooking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230721063355_UpdateEvent")]
    partial class UpdateEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.API.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinPrice")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("beb99d04-5d80-4031-a5d1-14e23a183754"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn-i.vtcnews.vn/resize/Da9xKKWytSr4nFIRCPjyxBQ21LK9PQ2a0/upload/2023/06/30/blackpink-07424148.jpg",
                            IsDeleted = false,
                            Location = "My Dinh stadium, Ha Noi",
                            MinPrice = 1000000,
                            Status = 0,
                            Title = "BlackPink world tour Ha Noi",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("83c49421-0027-4d33-aead-1a817fb2ba14"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://i.ytimg.com/vi/Qmlio2iEaJo/maxresdefault.jpg",
                            IsDeleted = false,
                            Location = "CGV Hung Vuong Plaza, Ho Chi Minh City",
                            MinPrice = 100000,
                            Status = 0,
                            Title = "Thor: Love and Thunder",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f96e74f8-8f0b-4cf1-a9db-4dcdea4a0da0"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.bongdaplus.vn/Assets/Media/2021/01/13/62/lich-thi-dau-v-league-2021-giai-doan-1.jpg",
                            IsDeleted = false,
                            Location = "Phu Tho Stadium, Ho Chi Minh City",
                            MinPrice = 120000,
                            Status = 0,
                            Title = "Viettel vs. Song Lam Nghe An",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("ee945eae-16fc-4a7c-9962-8a2eec9e65cc"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.bongdaplus.vn/Assets/Media/2021/01/13/62/lich-thi-dau-v-league-2021-giai-doan-1.jpg",
                            IsDeleted = false,
                            Location = "Sam Son Stadium, Binh Duong",
                            MinPrice = 120000,
                            Status = 0,
                            Title = "Becamex Binh Duong vs. Hoang Anh Gia Lai",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("6c163aab-0110-42ce-8d41-c9dab4684888"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://i.ytimg.com/vi/J7xEJnqlIuU/maxresdefault.jpg",
                            IsDeleted = false,
                            Location = "Nu Cuoi Moi theater, Ho Chi Minh City",
                            MinPrice = 200000,
                            Status = 0,
                            Title = "Liveshow Nu Cuoi Moi",
                            Type = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
