// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.API.EF;

#nullable disable

namespace TicketBooking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.API.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("697e2858-9716-4457-98b0-90c15e1cae52"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn-i.vtcnews.vn/resize/Da9xKKWytSr4nFIRCPjyxBQ21LK9PQ2a0/upload/2023/06/30/blackpink-07424148.jpg",
                            IsDeleted = false,
                            Location = "My Dinh stadium, Ha Noi",
                            Price = 1000000,
                            Status = 0,
                            Title = "BlackPink world tour Ha Noi",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("08ec5cda-2167-4763-8062-a35ef7dca916"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://i.ytimg.com/vi/Qmlio2iEaJo/maxresdefault.jpg",
                            IsDeleted = false,
                            Location = "CGV Hung Vuong Plaza, Ho Chi Minh City",
                            Price = 100000,
                            Status = 0,
                            Title = "Thor: Love and Thunder",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e2244242-d47b-4002-a1a0-eda359443f17"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.bongdaplus.vn/Assets/Media/2021/01/13/62/lich-thi-dau-v-league-2021-giai-doan-1.jpg",
                            IsDeleted = false,
                            Location = "Phu Tho Stadium, Ho Chi Minh City",
                            Price = 120000,
                            Status = 0,
                            Title = "Viettel vs. Song Lam Nghe An",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cf4f93bb-c097-470f-b5f8-665a2c46e4d7"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.bongdaplus.vn/Assets/Media/2021/01/13/62/lich-thi-dau-v-league-2021-giai-doan-1.jpg",
                            IsDeleted = false,
                            Location = "Sam Son Stadium, Binh Duong",
                            Price = 120000,
                            Status = 0,
                            Title = "Becamex Binh Duong vs. Hoang Anh Gia Lai",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("87eb9e31-e58d-4681-af0b-44ff79a0639b"),
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://i.ytimg.com/vi/J7xEJnqlIuU/maxresdefault.jpg",
                            IsDeleted = false,
                            Location = "Nu Cuoi Moi theater, Ho Chi Minh City",
                            Price = 200000,
                            Status = 0,
                            Title = "Liveshow Nu Cuoi Moi",
                            Type = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
